'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useUiStore } from '../lib/ui-store';
const links = [['/home', 'Home'], ['/explore', 'Explore'], ['/notifications', 'Notifications'], ['/messages', 'Messages'], ['/settings', 'Settings'], ['/profile/demo', 'Profile']];
export function Shell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const { mobileNavOpen, closeMobileNav, toggleMobileNav } = useUiStore();
  return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-20 border-b bg-white/90 px-4 py-3 backdrop-blur lg:hidden"><div className="flex items-center justify-between"><Link className="text-xl font-black text-blue-600" href="/home">Funspot</Link><button aria-label="Toggle navigation" onClick={toggleMobileNav} className="rounded-lg border px-3 py-1">Menu</button></div></header><div className="mx-auto grid max-w-7xl grid-cols-1 gap-6 px-4 lg:grid-cols-[220px_minmax(0,1fr)_260px]"><aside className={`${mobileNavOpen ? 'block' : 'hidden'} fixed inset-x-0 top-[58px] z-10 bg-white p-4 lg:static lg:block lg:bg-transparent lg:p-0 lg:pt-8`}><Link onClick={closeMobileNav} className="mb-8 hidden text-2xl font-black text-blue-600 lg:block" href="/home">Funspot</Link><nav className="grid gap-2">{links.map(([href, label]) => <Link onClick={closeMobileNav} className={`rounded-xl px-4 py-3 font-semibold ${pathname === href ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100'}`} href={href} key={href}>{label}</Link>)}</nav></aside><main className="min-w-0 py-6 lg:py-8">{children}</main><aside className="hidden pt-8 lg:block"><div className="rounded-2xl border bg-white p-5"><p className="font-bold">Discover Funspot</p><p className="mt-2 text-sm text-slate-500">Find people and conversations worth following.</p><Link className="mt-4 inline-block font-semibold text-blue-600" href="/explore">Explore now →</Link></div></aside></div></div>;
}
